version: '3.6'

services:
  tracker1:
    container_name: tracker1
    build:
      context: tracker-backend
      dockerfile: Dockerfile
      args:
        - PORT=8081
    ports:
      - 8081:8081
    networks:
      - network
  tracker2:
    container_name: tracker2
    build:
      context: tracker-backend
      dockerfile: Dockerfile
      args:
        - PORT=8082
    ports:
      - 8082:8082
    networks:
      - network
  tracker3:
    container_name: tracker3
    build:
      context: tracker-backend
      dockerfile: Dockerfile
      args:
        - PORT=8083
    ports:
      - 8083:8083
    networks:
      - network
networks:
  network:
