version: '3.6'

services:
  tracker1:
    container_name: tracker1
    hostname: tracker1
    build:
      context: tracker-backend
      dockerfile: Dockerfile
      args:
        - PORT=7001
    ports:
      - 7001:7001
    networks:
      - network
  tracker2:
    container_name: tracker2
    hostname: tracker2
    build:
      context: tracker-backend
      dockerfile: Dockerfile
      args:
        - PORT=7002
    ports:
      - 7002:7002
    networks:
      - network
  tracker3:
    container_name: tracker3
    hostname: tracker3
    build:
      context: tracker-backend
      dockerfile: Dockerfile
      args:
        - PORT=7003
    ports:
      - 7003:7003
    networks:
      - network
  client1:
    container_name: client1
    hostname: client1
    build:
      context: client-backend
      dockerfile: Dockerfile
      args:
        - PORT=6001
        - TRACKER_PREFIX=http://tracker
    ports:
      - 6001:6001
    networks:
      - network
  client2:
    container_name: client2
    hostname: client2
    build:
      context: client-backend
      dockerfile: Dockerfile
      args:
        - PORT=6002
        - TRACKER_PREFIX=http://tracker
    ports:
      - 6002:6002
    networks:
      - network
  client3:
    container_name: client3
    hostname: client3
    build:
      context: client-backend
      dockerfile: Dockerfile
      args:
        - PORT=6003
        - TRACKER_PREFIX=http://tracker
    ports:
      - 6003:6003
    networks:
      - network
  client4:
    container_name: client4
    hostname: client4
    build:
      context: client-backend
      dockerfile: Dockerfile
      args:
        - PORT=6004
        - TRACKER_PREFIX=http://tracker
    ports:
      - 6004:6004
    networks:
      - network

networks:
  network:
